# This is a workflow will help to generate china & us ip address pool

name: Daily update IP address

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dailyupdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          "token": ${{ secrets.GITHUB_TOKEN }}

      - name: Run a multi-line script
        run: |
          echo "Daily Scheduling update"
          git config --global user.email "hooaosir@163.com"
          git config --global user.name "hooao"
          cd $GITHUB_WORKSPACE && ./update.sh --nopush
      - name: push code to master
        run: git push origin master
